---
title: "blog-1"
description: |
  A short description of the post.
author:
  - name: Nora Jones
    url: https://example.com/norajones
date: 08-19-2021
output:
  distill::distill_article:
    self_contained: false
---



```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(tidycovid19)
df <- download_merged_data(cached = TRUE, silent = TRUE)
```

```{r crunch-numbers}
ausdf <- df %>% 
  filter(country=="Australia")

last_date <- ausdf %>% 
  pull(date) %>% 
  max()

last_cases <- ausdf %>% 
  filter(date %in% c(last_date - 1, last_date)) %>% 
  pull(confirmed) %>% 
  diff()
```
There was **`r last_cases`** confirmed cases reported in Australia on **`r last_date`**.


```{r covid-stripes, out.extra = "class='border'"}
plot_covid19_stripes(df, 
                     countries = c("AUS", "CHN", "IND",
                                   "JPN", "SGP", "USA"), 
                     type = "confirmed")
```


```{css}
.author {
  font-family:cursive
}

```

```{css}
body{
  background-color:black
  }
```

```{css}
header {
  style:white
}
```

